In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
df= pd.read_csv('Churn_Modelling.csv')
X= df.iloc[:, 3:-1].values
y= df.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X)) 

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
ann = tf.keras.models.Sequential()

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [19]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy', metrics = ['accuracy'])

In [20]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
219/219 [==============================] - 4s 2ms/step - loss: 0.5194 - accuracy: 0.7977
Epoch 2/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4581 - accuracy: 0.7977
Epoch 3/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4422 - accuracy: 0.7973
Epoch 4/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4338 - accuracy: 0.7996
Epoch 5/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4282 - accuracy: 0.8076
Epoch 6/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4229 - accuracy: 0.8153
Epoch 7/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4168 - accuracy: 0.8184
Epoch 8/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4112 - accuracy: 0.8207
Epoch 9/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4064 - accuracy: 0.8236
Epoch 10/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4017 - accura

In [21]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

94/94 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2299   80]
 [ 339  282]]


0.8603333333333333

In [28]:
ann.save('Churn')

INFO:tensorflow:Assets written to: Churn\assets


INFO:tensorflow:Assets written to: Churn\assets


In [29]:
from tensorflow import keras
model = keras.models.load_model('Churn')

In [30]:

print(model.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 61ms/step
[[False]]
